# src/agents/report_generator.py
from typing import Dict

def report_generator(state: Dict) -> Dict:
    report = state.get("report", "")
    citations = state.get("citations", [])
    
    if citations:
        citation_text = "\n".join(f"- {c}" for c in citations)
    else:
        citation_text = "No citations available."
    
    formatted_report = f"# Research Summary Report\n\n{report}\n\n📚 Citations:\n{citation_text}\n\n*Generated by Research Agent*"
    
    state["final_report"] = formatted_report
    return state

