# src/agents/report_generator.py
from typing import Dict

def report_generator(state: Dict) -> Dict:
    report = state.get("report", "")
    
    # Simple formatting — you can enhance as needed
    formatted_report = f"# Research Summary Report\n\n{report}\n\n*Generated by Research Agent*"
    
    state["final_report"] = formatted_report
    return state
